version: '3'

services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-petsyappuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ESB12019}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - petsy
    restart: unless-stopped
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/petsyApp
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - petsy

networks:
  petsy:
    driver: bridge

volumes:
    db-data:
        driver: local