# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-06 16:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import petsy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('nameProduct', models.CharField(max_length=30)),
                ('idProduct', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('Joya', 'Joyeria y complementos'), ('Ropa', 'Ropa y calzado'), ('Casa', 'Hogar y decoracion'), ('Boda', 'Bodas y fiestas'), ('Toys', 'Juguetes y ocio'), ('Cole', 'Arte y objetos de decoración'), ('Arte', 'Herramientas para la artesania'), ('Vint', 'Vintage'), ('Otro', 'Otras categorias')], default='Otro', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('materials', models.TextField(default='')),
                ('sold', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to=petsy.models.get_image_filename_post)),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('num_votes', models.IntegerField(default=0)),
                ('sum_votes', models.IntegerField(default=0)),
                ('reviews', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1, 'Value must be between 1 and 5'), django.core.validators.MaxValueValidator(5, 'Value must be between 1 and 5')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsy.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id_shop', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.TextField(default='Shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopFavorited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserPetsy',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, default='default_user.png', max_length=500, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('init_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='petsy.UserPetsy'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='petsy.UserPetsy'),
        ),
        migrations.AddField(
            model_name='shopfavorited',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_faved', to='petsy.UserPetsy'),
        ),
        migrations.AddField(
            model_name='shopfavorited',
            name='shop_faved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='petsy.Shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='user_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsy.UserPetsy'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_rev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsy.UserPetsy'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsy.Shop'),
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together=set([('follower', 'following')]),
        ),
        migrations.AlterUniqueTogether(
            name='shopfavorited',
            unique_together=set([('follower', 'shop_faved')]),
        ),
    ]
